/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MediaSession {
  constructor()
  setEventHandler(handler?: (((err: Error | null, arg: MediaSessionEvents) => void)) | undefined | null): void
  setMetadata(metadata?: SmtcMetadata | undefined | null): void
  setPlaybackStatus(status: string): void
  setPlaybackRate(rate: number): void
  /** Update the SMTC timeline. Both values are in 100 ns ticks. */
  setTimelineProperties(position: number, duration: number): void
}

/**
 * Whether this process can power the machine off.
 *
 * Enabling `SeShutdownPrivilege` is what the answer is based on: Windows grants
 * it to interactive users but leaves it disabled until it is asked for. This is
 * a capability check, not a guarantee: the system can still refuse the request
 * itself, for reasons this cannot see from here.
 */
export declare function canShutdown(): boolean

export type MediaSessionEvents =
  | { type: 'Play' }
  | { type: 'Pause' }
  | { type: 'Next' }
  | { type: 'Previous' }
  | { type: 'Stop' }
  | { type: 'SetPosition', position: number }
  | { type: 'SetRate', rate: number }

/**
 * Power the machine off immediately.
 *
 * `message` is shown by the system while it shuts down, and
 * `force_apps_closed` decides whether applications with unsaved changes are
 * closed instead of blocking the shutdown.
 *
 * A shutdown that is already in progress counts as success: the machine is
 * going down either way, which is the state the caller asked for.
 */
export declare function shutdownNow(message: string, forceAppsClosed: boolean): void

export interface SmtcMetadata {
  title?: string
  artist?: string
  album?: string
  albumArtist?: string
  artUrl?: string
}
