import { join } from "node:path";
import { mkdir, writeFile } from "node:fs/promises";

import yaml from "yaml";

// Shared Flatpak builder-manifest generation. Consumed by:
//  - scripts/build-flatpak-builder.ts  (Flathub: compiles inside the sandbox)
//  - plugins/MakerFlatpak.ts           (prebuilt: reuses the packaged app)

const RUNTIME = "org.freedesktop.Platform";
const SDK = "org.freedesktop.Sdk";
const BASE = "org.electronjs.Electron2.BaseApp";
const NODE_EXTENSION = "org.freedesktop.Sdk.Extension.node24";

// Electron always bundles chrome-sandbox, so the app is launched through the
// zypak electron-wrapper shim generated by build-scaffold.ts
// (`--with-zypak-wrapper`). `zypak-wrapper` itself is provided by the Electron
// base app, so no zypak module is needed.
export const DESKTOP_EXEC = "electron-wrapper";

export interface ManifestContext {
  appId: string;
  appIdentifier: string;
  runtimeVersion: string;
  baseVersion: string;
  finishArgs: string[];
  /** Flatpak branch (default: "stable"). */
  branch?: string;
  /** SDK extensions. Prebuilt builds need none (default: node24 for source builds). */
  sdkExtensions?: string[];
  /** Extra manifest modules appended before the app module. */
  extraModules?: unknown[];
}

/** Assemble the top-level manifest shared by every variant. */
export function baseManifest(ctx: ManifestContext, appModule: unknown) {
  const sdkExtensions = ctx.sdkExtensions ?? [NODE_EXTENSION];
  const manifest: Record<string, unknown> = {
    "app-id": ctx.appId,
    runtime: RUNTIME,
    "runtime-version": ctx.runtimeVersion,
    sdk: SDK,
    base: BASE,
    "base-version": ctx.baseVersion,
    branch: ctx.branch ?? "stable",
    command: DESKTOP_EXEC,
    "separate-locales": false,
    "finish-args": ctx.finishArgs,
    modules: [...(ctx.extraModules ?? []), appModule],
  };
  if (sdkExtensions.length > 0) {
    manifest["sdk-extensions"] = sdkExtensions;
  }
  return manifest;
}

export interface PrebuiltAppModuleOptions {
  /** Bundled payload tarball (app/, scaffold/, metainfo) relative to the manifest dir. */
  appBundle: string;
  /** Metainfo filename inside the bundle. */
  metainfo: string;
}

/**
 * The app module for a PREBUILT build: the packaged app, the scaffold and the
 * metainfo are all bundled on the host (where node_modules exists), so the
 * sandbox just copies them into /app — no toolchain, no node.
 */
export function prebuiltAppModule(
  ctx: ManifestContext,
  opts: PrebuiltAppModuleOptions
) {
  return {
    name: ctx.appIdentifier,
    buildsystem: "simple",
    "build-commands": [
      // The archive source is auto-extracted by flatpak-builder, so scaffold/
      // and app/ are already in the build dir.
      `cp -r scaffold/. /app/`,
      `install -d /app/lib/${ctx.appIdentifier}`,
      `cp -r app/. /app/lib/${ctx.appIdentifier}/`,
      `install -Dm644 ${opts.metainfo} /app/share/metainfo/${ctx.appId}.metainfo.xml`,
    ],
    sources: [{ type: "archive", path: opts.appBundle }],
  };
}

/** Write a manifest to `<outDir>/<app-id>.yaml`; returns the file path. */
export async function writeManifest(
  outDir: string,
  manifest: Record<string, unknown>
): Promise<string> {
  await mkdir(outDir, { recursive: true });
  const doc = yaml.parseDocument(yaml.stringify(manifest));
  const manifestPath = join(outDir, `${manifest["app-id"]}.yaml`);
  await writeFile(manifestPath, doc.toString());
  return manifestPath;
}
