/**
 * In audio worklet context, {@link TextDecoder} doesn't exist, use this module to make
 * WASM module generated by `wasm-bindgen` to run without an issue in audio worklet context.
 *
 * If encounters any problem with the WASM module within the audio worklet context, you may need
 * to use a proper polyfill of {@link TextDecoder} to get more debug information.
 */
class MockTextDecoder {
  decode() {
    return "";
  }
}
globalThis.TextDecoder = MockTextDecoder as unknown as typeof TextDecoder;
