/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Withdraw a layer-shell declaration that has not been consumed yet. */
export declare function cancelLayerShellForNextWindow(): boolean

/**
 * Listen for first CursorEnter event of the next created window.
 *
 * Only for Wayland on Linux.
 */
export declare function captureNextWindowFirstCursorEnter(callback: (x: number, y: number) => void): void

export declare const enum DesktopEnvironment {
  Wayland = 0,
  X11 = 1,
  Windows = 2,
  Darwin = 3,
  Unknown = 4
}

export declare function dragWindow(hwnd: Buffer): void

/**
 * Gets the position of the cursor
 *
 * Only for X11 on Linux.
 */
export declare function getCursorPosition(): [number, number] | null

/**
 * Get current detected desktop environment.
 *
 * Mostly for Linux to use, on Windows/macOS, returns hardcoded values.
 */
export declare function getDesktopEnvironment(): DesktopEnvironment

/**
 * Whether the compositor advertises `zwlr_layer_shell_v1`.
 *
 * Only meaningful for Wayland on Linux; everywhere else it is `false`.
 */
export declare function isLayerShellAvailable(): boolean

/** The stacking layer a layer surface is placed in, bottom-most first. */
export declare const enum LayerShellLayer {
  Background = 0,
  Bottom = 1,
  Top = 2,
  Overlay = 3
}

/**
 * Layer-shell state for a window the application is about to create.
 *
 * Applied to the next toplevel the display connection creates, so it has to be
 * declared before the window (or its surface) is brought into existence. A
 * declaration that says nothing about size or anchors covers the output.
 */
export interface LayerShellOptions {
  /** Purpose of the surface, e.g. `"open-orpheus-menu"`. Required. */
  namespace: string
  /** Defaults to the top layer. */
  layer?: LayerShellLayer
  anchorTop?: boolean
  anchorBottom?: boolean
  anchorLeft?: boolean
  anchorRight?: boolean
  /**
   * Surface size in surface-local coordinates. `0` lets the compositor
   * decide, which requires the two opposite anchors on that axis.
   */
  width?: number
  height?: number
  marginTop?: number
  marginRight?: number
  marginBottom?: number
  marginLeft?: number
  /** `-1` ignore other surfaces, `0` avoid them, `>0` reserve space. */
  exclusiveZone?: number
  /** `0` none, `1` exclusive, `2` on demand (needs layer shell v4). */
  keyboardInteractivity?: number
}

/**
 * Set regions that the window is used to receive inputs.
 *
 * Only for Linux.
 */
export declare function setInputRegion(windowHandle: string | Buffer, rects?: { x: number, y: number, w: number, h: number }[] | null): boolean

/**
 * Make the next window a layer surface.
 *
 * Must be called before the window — or, for an existing window, its surface —
 * is created: a compositor assigns a surface's role once and never changes it.
 * Returns whether the declaration was accepted; when it is refused the window
 * is still created as an ordinary one.
 */
export declare function useLayerShellForNextWindow(options: LayerShellOptions): boolean

/**
 * Whether a layer-shell declaration would be accepted.
 *
 * The same validation `useLayerShellForNextWindow` applies, without queueing
 * anything: callers can report a declaration that could never be sent, and a
 * settings UI can check a choice before anything is created. `false` also
 * means the compositor cannot take layer surfaces at all.
 */
export declare function validateLayerShellOptions(options: LayerShellOptions): boolean
