/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A decoder for AV3A audio inside an M4A / MP4 container.
 *
 * The constructor only needs the file's `moov` box to be present; it is read
 * once to build the sample index. Media samples are read straight from the
 * file on demand, so callers that stream a partially downloaded file should
 * wait for the range reported by [`nextSampleRange`] before each
 * [`decodeNext`].
 */
export declare class Av3AM4ADecoder {
  /** Open an M4A/MP4 file and index its AV3A track. */
  constructor(path: string)
  /** Track-level information for the opened file. */
  info(): object
  /** Track sample index that the next [`decodeNext`] call will read. */
  position(): number
  /**
   * Move to an exact track frame. The frames needed to warm the decoder's
   * overlap-add state are decoded and discarded on the following
   * [`decodeNext`] calls.
   */
  seekToFrame(index: number): void
  /**
   * Byte range of the sample the next [`decodeNext`] call will read, or
   * `done: true` at the end of the track. A caller that streams a partially
   * downloaded file can wait until these bytes are present before decoding.
   */
  nextSampleRange(): object
  /**
   * Byte range the next [`decodeNext`] call will read from the file. After
   * a seek this spans the discarded warm-up frames plus the returned frame,
   * so a streaming caller can wait until the whole window is downloaded
   * before decoding (never reading through zero-filled holes).
   */
  decodeWindowRange(): object
  /**
   * Decode the next frame to interleaved little-endian PCM16. Returns an
   * object with `done: true` once the end of the track is reached.
   */
  decodeNext(): object
  /**
   * Release the underlying file handle. Safe to call more than once; any
   * further method call returns an error.
   */
  close(): void
}
export type Av3aM4aDecoder = Av3AM4ADecoder
